fix: missing path-to-regexp dependency
Because it is no longer exported by universal-router. Was causing:

    Uncaught TypeError: D is not a function