docs: add package dependency graph diagrams
Just to visually sanity-check that things look reasonable, there are no
circular dependencies etc.

Partly motivated by my terrible memory, and partly because I have a
problem now where TS fails to find all modules on first build, but finds
them on second:

    $ git clean -fdx packages
    $ yarn build

    packages/benchmark/src/benchmark-static-lexer.ts:1:19 - error TS2307: Cannot find module '@masochist/graphql' or its corresponding type declarations.

    1 import {lex} from '@masochist/graphql';
                        ~~~~~~~~~~~~~~~~~~~~

    packages/benchmark/src/benchmark-static-parser.ts:1:29 - error TS2307: Cannot find module '@masochist/graphql' or its corresponding type declarations.

    1 import {parseDocument} from '@masochist/graphql';
                                  ~~~~~~~~~~~~~~~~~~~~

    packages/benchmark/src/benchmark-table-parser.ts:1:35 - error TS2307: Cannot find module '@masochist/graphql' or its corresponding type declarations.

    1 import {grammar, lex, table} from '@masochist/graphql';
                                        ~~~~~~~~~~~~~~~~~~~~
    $ yarn build
    ✨  Done in 1.62s.