chore: update jest 25.1.0 → 27.4.3
Busy work to make `yarn audit` less upset. But still upset.

Before:

    106 vulnerabilities found - Packages audited: 1592
    Severity: 3 Low | 77 Moderate | 26 High

After:

    65 vulnerabilities found - Packages audited: 1666
    Severity: 3 Low | 42 Moderate | 20 High

Note that I also needed to provide a `fail` function to avoid:

    ReferenceError: fail is not defined