style(lexer): fix lints
Of the form:

    packages/lexer/src/__tests__/build-test.ts:490:18 - error TS4111: Property 'startStates' comes from an index signature, so it must be accessed with ['startStates'].

    490     expect(stats.startStates).toBe(1);
                     ~~~~~~~~~~~