refactor: silence spurious TypeScript warning
It complains like this:

    error TS2366: Function lacks ending return statement and return type
    does not include 'undefined'.

Spurious because if you check the value of `node` at the end of the
function, TS knows that it is `never`. Note that I can't even log
`Unexpected \`node.kind\` ${node.kind}`, because TS says:

    Property 'kind' does not exist on type 'never'.