style: remove stray import
As reported by `yarn lint`:

    packages/lexer/src/RegExp/RegExpParser.ts:1:1 - error TS6192: All imports in import declaration are unused.

    1 import {describe, expect, it} from '@jest/globals';
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~