style(parser): fix lints in `validateGrammar()`
    error TS6133: 'grammar' is declared but its value is never read.
    error TS2304: Cannot find name 'Grammar'.

Still have to actually finish the implementation, and use it when
generating the parser.