fix: update npm packages
On new machine, we have a newer NodeJS, so we're running into this:

    Error: Cannot find module '$path_to/@babel/compat-data/data/corejs3-shipped-proposals'

Which I think is the issue described here:

    https://github.com/nodejs/node/issues/32852

and fixed here:

    https://github.com/babel/babel/pull/11283

I just ran `yarn upgrade-interactive` and updated all the packages which
looked safe-ish.