fix: correct a number of problems reported by `yarn lint`
Fixes these six problems:

    packages/lexer/src/RegExp/RegExpParser.ts:143:31 - error TS4111: Property 'd' comes from an index signature, so it must be accessed with ['d'].

    143   D: {...BASE_SPECIAL_CLASSES.d, negated: true} as CharacterClass,
                                      ~
    packages/lexer/src/RegExp/RegExpParser.ts:144:31 - error TS4111: Property 's' comes from an index signature, so it must be accessed with ['s'].

    144   S: {...BASE_SPECIAL_CLASSES.s, negated: true} as CharacterClass,
                                      ~
    packages/lexer/src/RegExp/RegExpParser.ts:145:31 - error TS4111: Property 'w' comes from an index signature, so it must be accessed with ['w'].

    145   W: {...BASE_SPECIAL_CLASSES.w, negated: true} as CharacterClass,
                                      ~
    packages/lexer/src/NFA/removeEpsilons.ts:5:1 - error TS6133: 'stringifyTransition' is declared but its value is never read.

    5 import stringifyTransition from './stringifyTransition';
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    packages/lexer/src/NFA/stringifyTransitionTable.ts:116:10 - error TS6133: 'formatSet' is declared but its value is never read.

    116 function formatSet(set?: Set<string>): string {
                 ~~~~~~~~~

    packages/lexer/src/NFA/__tests__/dotifyTransitionTable-test.ts:15:3 - error TS6133: 'INTEGER_PART' is declared but its value is never read.

    15   INTEGER_PART,
         ~~~~~~~~~~~~