Revert "Point graphql-relay dependency at my fork"
This reverts commit 83d8f15c1e561e95d82b1753f7455677300531d1.

Not sure why, but when using a Git module as a dependency, things blow
up with:

    Error: Cannot find module 'graphql-relay'

So, will worry about this later.