chore: change from pnp to pnpm
ie.

- from "a single Node.js loader file will be generated"
- to "a `node-modules` will be created using symlinks and hardlinks to a
  global content-addressable store"

Source: https://yarnpkg.com/configuration/yarnrc#nodeLinker

Resulting tree:

    node_modules
    ├── @jest
    │   └── globals -> ../.store/@jest-globals-npm-29.6.4-2c74983df1/node_modules/@jest/globals
    ├── @types
    │   └── node -> ../.store/@types-node-npm-20.5.7-b5e80f1922/node_modules/@types/node
    ├── jest -> .store/jest-virtual-0fd8f97523/node_modules/jest
    ├── jest-config -> .store/jest-config-virtual-4432a42ab5/node_modules/jest-config
    ├── prettier -> .store/prettier-npm-3.0.3-fced695dae/node_modules/prettier
    ├── prettier-v2-for-jest-inline-snapshots -> .store/prettier-npm-2.8.8-430828a36c/node_modules/prettier
    ├── ts-jest -> .store/ts-jest-virtual-eb33143e6d/node_modules/ts-jest
    └── typescript -> .store/typescript-patch-2e8dbfb8ab/node_modules/typescript

This moves us from two inscrutable errors that I can't solve:

    packages/common/src/__tests__/Queue-test.ts:1:36 - error TS2307: Cannot find module '@jest/globals' or its corresponding type declarations.

    1 import {describe, expect, it} from '@jest/globals';
                                         ~~~~~~~~~~~~~~~

    packages/common/src/__tests__/StringScanner-test.ts:1:48 - error TS2307: Cannot find module '@jest/globals' or its corresponding type declarations.

    1 import {beforeEach, describe, expect, it} from '@jest/globals';
                                                 ~~~~~~~~~~~~~~~

to two errors that I can solve:

    packages/lexer/src/RegExp/__tests__/normalizeCharacterClass-test.ts:1:27 - error TS2305: Module '"@jest/globals"' has no exported member 'fail'.

    1 import {describe, expect, fail, it} from '@jest/globals';
                                ~~~~

    packages/legacy/src/lexer/__tests__/Lexer-test.ts:483:14 - error TS2571: Object is of type 'unknown'.

    483       expect(onMatch.mock.calls[0][0][0]).toBe('foo');
                     ~~~~~~~~~~~~~~~~~~~~~~~~

Some related issues/PRs shed light on the long and difficult road to get
Typescript and Yarn PNP to play together:

- https://github.com/yarnpkg/berry/issues/589
- https://github.com/Microsoft/TypeScript/issues/28289
- https://github.com/microsoft/TypeScript/pull/35206

I am actually surprised that it worked as well as it did. But those last
couple errors, not sure how to solve them or even begin troubleshooting
them.