refactor: satisfy new version of TypeScript
Which was spitting out this rather nasty looking thing:

      packages/lexer/src/RegExp/RegExpParser.ts:152:39 - error TS2769: No overload matches this call.
      Overload 1 of 2, '(o: { [s: string]: unknown; } | ArrayLike<unknown>): unknown[]', gave the following error.
        Argument of type '(T & object) | (T & null)' is not assignable to parameter of type '{ [s: string]: unknown; } | ArrayLike<unknown>'.
          Type 'T & object' is not assignable to type '{ [s: string]: unknown; } | ArrayLike<unknown>'.
            Property 'length' is missing in type '{}' but required in type 'ArrayLike<unknown>'.
      Overload 2 of 2, '(o: {}): any[]', gave the following error.
        Argument of type '(T & object) | (T & null)' is not assignable to parameter of type '{}'.
          Type 'T & null' is not assignable to type '{}'.

    152     for (const value of Object.values(object)) {
                                              ~~~~~~