chore: switch to pnp
This almost works, but for two errors:

    packages/common/src/__tests__/Queue-test.ts:1:36 - error TS2307: Cannot find module '@jest/globals' or its corresponding type declarations.

    1 import {describe, expect, it} from '@jest/globals';
                                         ~~~~~~~~~~~~~~~

    packages/common/src/__tests__/StringScanner-test.ts:1:48 - error TS2307: Cannot find module '@jest/globals' or its corresponding type declarations.

    1 import {beforeEach, describe, expect, it} from '@jest/globals';
                                                     ~~~~~~~~~~~~~~~

No idea why it is complaining about these two files, but none of the
others.