style: fix another lint
    packages/parser/src/parseDSL.ts:1:1 - error TS6192: All imports in import declaration are unused.

    1 import {describe, expect, it} from '@jest/globals';
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Not sure why it didn't show up the last time (a couple of commits ago,
in 8404e51bd, "style: remove stray import", 30 Aug 2023).