chore: update webpack-dev-server
Note that I had to go through a few tweak-restart loops to flush out all
the problems:

    ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
     - options has an unknown property 'noInfo'. These properties are valid:

    ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
    - options has an unknown property 'publicPath'. These properties are valid:

    (node:46306) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.

    (node:46332) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use async 'start' or 'startCallback' methods.

    <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.