chore: update tsconfig-base.json
Generated a new file with `tsc --init` in an empty directory (ie.
v5.2.2) then applied updates:

1.   Uncommented `"composite": true` setting; without this, we get these
     two errors (although I am not sure why we only get two):

          packages/codegen/tsconfig.json:8:18 - error TS6306: Referenced project '/Users/wincent/code/masochist-experimental/packages/common' must have setting "composite": true.

          8   "references": [{"path": "../common"}]
                             ~~~~~~~~~~~~~~~~~~~~~

          packages/legacy/tsconfig.json:8:18 - error TS6306: Referenced project '/Users/wincent/code/masochist-experimental/packages/common' must have setting "composite": true.

          8   "references": [{"path": "../common"}]
                             ~~~~~~~~~~~~~~~~~~~~~

2.  Set "target" to "ES2020" (was "es2019"), not that I expect it to
    make any significant difference.

3.  Added "extends" at bottom, maintaining the hack added in
    6246a38dc1b12a562 ("feat: implement inglorious hack to make `yarn
    lint` work", Feb 2, 2022).