test: fix a new type error
    packages/lexer/src/RegExp/__tests__/normalizeCharacterClass-test.ts:163:36 - error TS2345: Argument of type 'Node' is not assignable to parameter of type 'CharacterClass'.
      Type 'Atom' is missing the following properties from type 'CharacterClass': children, negated

    163     expect(normalizeCharacterClass(characterClass)).toEqual({
                                           ~~~~~~~~~~~~~~